/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AutomaticPlayerSkillLevel {
    #[serde(rename = "Beginner")]
    Beginner,
    #[serde(rename = "Intermediate")]
    Intermediate,
    #[serde(rename = "Expert")]
    Expert,
    #[serde(rename = "Master")]
    Master,

}

impl std::fmt::Display for AutomaticPlayerSkillLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Beginner => write!(f, "Beginner"),
            Self::Intermediate => write!(f, "Intermediate"),
            Self::Expert => write!(f, "Expert"),
            Self::Master => write!(f, "Master"),
        }
    }
}

impl Default for AutomaticPlayerSkillLevel {
    fn default() -> AutomaticPlayerSkillLevel {
        Self::Beginner
    }
}

