/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EndGameParams : Models info needed to end a Game
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndGameParams {
    /// ID of one of the Players in the Gaming Session
    #[serde(rename = "player_id")]
    pub player_id: String,
    /// ID of the Gaming Session in which the Game is being played
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl EndGameParams {
    /// Models info needed to end a Game
    pub fn new(player_id: String, session_id: String) -> EndGameParams {
        EndGameParams {
            player_id,
            session_id,
        }
    }
}

