/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EndGamingSessionParams : Models info needed to end a Gaming Session.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndGamingSessionParams {
    #[serde(rename = "player_id")]
    pub player_id: String,
}

impl EndGamingSessionParams {
    /// Models info needed to end a Gaming Session.
    pub fn new(player_id: String) -> EndGamingSessionParams {
        EndGamingSessionParams {
            player_id,
        }
    }
}

