/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: Info@RustMadeEasy.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventPlaneConfig : Models the configuration required for clients subscribe to real-time game state updates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPlaneConfig {
    /// Address of the real-time messaging broker.
    #[serde(rename = "broker_address")]
    pub broker_address: String,
    /// Broker port number of the real-time messaging broker.
    #[serde(rename = "broker_port")]
    pub broker_port: i32,
    /// The topic prefix that allows the clients to subscribe to real-time game state updates.
    #[serde(rename = "topic_prefix")]
    pub topic_prefix: String,
}

impl EventPlaneConfig {
    /// Models the configuration required for clients subscribe to real-time game state updates.
    pub fn new(broker_address: String, broker_port: i32, topic_prefix: String) -> EventPlaneConfig {
        EventPlaneConfig {
            broker_address,
            broker_port,
            topic_prefix,
        }
    }
}

