/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameInfo : Models the current view of a Game.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameInfo {
    #[serde(rename = "current_player", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_player: Option<Option<models::PlayerInfo>>,
    #[serde(rename = "game_state")]
    pub game_state: models::GameState,
    /// Unique ID of the Game instance
    #[serde(rename = "id")]
    pub id: String,
    /// List of Players
    #[serde(rename = "players")]
    pub players: Vec<models::PlayerInfo>,
}

impl GameInfo {
    /// Models the current view of a Game.
    pub fn new(game_state: models::GameState, id: String, players: Vec<models::PlayerInfo>) -> GameInfo {
        GameInfo {
            current_player: None,
            game_state,
            id,
            players,
        }
    }
}

