/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameState : Models the state of a Game at a particular Move (turn).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameState {
    /// Specifies the layout of the Game Pieces for this particular Game State.
    #[serde(rename = "game_board")]
    pub game_board: Vec<Vec<models::GamePiece>>,
    /// ID of the Player who made the Move that brought about this Game State.
    #[serde(rename = "id_of_player_who_made_move")]
    pub id_of_player_who_made_move: String,
    /// The current status of the Game.
    #[serde(rename = "play_status")]
    pub play_status: models::PlayStatus,
}

impl GameState {
    /// Models the state of a Game at a particular Move (turn).
    pub fn new(game_board: Vec<Vec<models::GamePiece>>, id_of_player_who_made_move: String, play_status: models::PlayStatus) -> GameState {
        GameState {
            game_board,
            id_of_player_who_made_move,
            play_status,
        }
    }
}

