/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: Support@RustMadeEasy.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// GamePiece : Models a Game Piece with which the Tic-Tac-Toe game is played.
/// Models a Game Piece with which the Tic-Tac-Toe game is played.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GamePiece {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "X")]
    X,
    #[serde(rename = "O")]
    O,
}

impl ToString for GamePiece {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::X => String::from("X"),
            Self::O => String::from("O"),
        }
    }
}

impl Default for GamePiece {
    fn default() -> GamePiece {
        Self::None
    }
}
