/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameMode : Specifies the type of Game - single player or two players.
/// Specifies the type of Game - single player or two players.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GameMode {
    #[serde(rename = "SinglePlayer")]
    SinglePlayer,
    #[serde(rename = "TwoPlayers")]
    TwoPlayers,

}

impl std::fmt::Display for GameMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SinglePlayer => write!(f, "SinglePlayer"),
            Self::TwoPlayers => write!(f, "TwoPlayers"),
        }
    }
}

impl Default for GameMode {
    fn default() -> GameMode {
        Self::SinglePlayer
    }
}

