/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GamingSessionCreationResponse : Models the results of a call to the Create Gaming Session endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamingSessionCreationResponse {
    /// Specifies the configuration required for clients to subscribe to real-time Game state updates
    #[serde(rename = "event_plane_config")]
    pub event_plane_config: models::EventPlaneConfig,
    /// The Player who initiated the Gaming Session
    #[serde(rename = "initiating_player")]
    pub initiating_player: models::PlayerInfo,
    /// Unique Code that is used to invite other participants to the Gaming Session
    #[serde(rename = "invitation_code")]
    pub invitation_code: String,
    /// ID of the additional Player
    #[serde(rename = "other_player", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub other_player: Option<Option<models::PlayerInfo>>,
    /// Identifies the Gaming Session. This also serves as the communication channel for MQTT notifications.
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl GamingSessionCreationResponse {
    /// Models the results of a call to the Create Gaming Session endpoint
    pub fn new(event_plane_config: models::EventPlaneConfig, initiating_player: models::PlayerInfo, invitation_code: String, session_id: String) -> GamingSessionCreationResponse {
        GamingSessionCreationResponse {
            event_plane_config,
            initiating_player,
            invitation_code,
            other_player: None,
            session_id,
        }
    }
}

