/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JoinSessionParams : Models info needed to join a Gaming Session.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JoinSessionParams {
    #[serde(rename = "game_invitation_code")]
    pub game_invitation_code: String,
    #[serde(rename = "player_display_name")]
    pub player_display_name: String,
}

impl JoinSessionParams {
    /// Models info needed to join a Gaming Session.
    pub fn new(game_invitation_code: String, player_display_name: String) -> JoinSessionParams {
        JoinSessionParams {
            game_invitation_code,
            player_display_name,
        }
    }
}

