/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewSinglePlayerGameParams : Models info needed to start a new Single-Player Game.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewSinglePlayerGameParams {
    #[serde(rename = "computer_skill_level")]
    pub computer_skill_level: models::AutomaticPlayerSkillLevel,
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl NewSinglePlayerGameParams {
    /// Models info needed to start a new Single-Player Game.
    pub fn new(computer_skill_level: models::AutomaticPlayerSkillLevel, session_id: String) -> NewSinglePlayerGameParams {
        NewSinglePlayerGameParams {
            computer_skill_level,
            session_id,
        }
    }
}

