/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewSinglePlayerGameParams : Models info needed to start a new Single-Player Game
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewSinglePlayerGameParams {
    /// The skill level at which the Automatic Player is to play the Game
    #[serde(rename = "computer_skill_level")]
    pub computer_skill_level: models::AutomaticPlayerSkillLevel,
}

impl NewSinglePlayerGameParams {
    /// Models info needed to start a new Single-Player Game
    pub fn new(computer_skill_level: models::AutomaticPlayerSkillLevel) -> NewSinglePlayerGameParams {
        NewSinglePlayerGameParams {
            computer_skill_level,
        }
    }
}

