/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewGameParams : Models info needed to start a new Game.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewGameParams {
    #[serde(rename = "game_mode")]
    pub game_mode: models::GameMode,
    #[serde(rename = "player_one_display_name")]
    pub player_one_display_name: String,
    #[serde(rename = "single_player_skill_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub single_player_skill_level: Option<Option<models::AutomaticPlayerSkillLevel>>,
}

impl NewGameParams {
    /// Models info needed to start a new Game.
    pub fn new(game_mode: models::GameMode, player_one_display_name: String) -> NewGameParams {
        NewGameParams {
            game_mode,
            player_one_display_name,
            single_player_skill_level: None,
        }
    }
}

