/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewGamingSessionParams : Models info needed to start a new Gaming Session
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewGamingSessionParams {
    /// The proposed display name of the Player
    #[serde(rename = "session_owner_display_name")]
    pub session_owner_display_name: String,
}

impl NewGamingSessionParams {
    /// Models info needed to start a new Gaming Session
    pub fn new(session_owner_display_name: String) -> NewGamingSessionParams {
        NewGamingSessionParams {
            session_owner_display_name,
        }
    }
}

