/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewTwoPlayerGameParams : Models info needed to start a new Two-Player Game.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewTwoPlayerGameParams {
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl NewTwoPlayerGameParams {
    /// Models info needed to start a new Two-Player Game.
    pub fn new(session_id: String) -> NewTwoPlayerGameParams {
        NewTwoPlayerGameParams {
            session_id,
        }
    }
}

