/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlayerInfo : Models a Tic-Tac-Toe Game Player.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayerInfo {
    /// Name of the Player.
    #[serde(rename = "display_name")]
    pub display_name: String,
    /// The Game Piece assigned to the Player.
    #[serde(rename = "game_piece")]
    pub game_piece: models::GamePiece,
    /// Indicates that this Player's moves are automated, i.e., guided by this service.
    #[serde(rename = "is_automated")]
    pub is_automated: bool,
    /// Unique ID of the Player.
    #[serde(rename = "player_id")]
    pub player_id: String,
}

impl PlayerInfo {
    /// Models a Tic-Tac-Toe Game Player.
    pub fn new(display_name: String, game_piece: models::GamePiece, is_automated: bool, player_id: String) -> PlayerInfo {
        PlayerInfo {
            display_name,
            game_piece,
            is_automated,
            player_id,
        }
    }
}

