/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: JoelDavisEngineering@Gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlayersReadinessResponse : Models the results of a call to the Get Players' Readiness end point
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayersReadinessResponse {
    /// Indicates whether the Game's Players are ready.
    #[serde(rename = "all_players_are_ready")]
    pub all_players_are_ready: bool,
}

impl PlayersReadinessResponse {
    /// Models the results of a call to the Get Players' Readiness end point
    pub fn new(all_players_are_ready: bool) -> PlayersReadinessResponse {
        PlayersReadinessResponse {
            all_players_are_ready,
        }
    }
}

