/*
 * Tic-Tac-Toe Service
 *
 * Tic-Tac-Toe Game Service
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: Support@RustMadeEasy.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PlayStatus : Lists valid game play statuses.
/// Lists valid game play statuses.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlayStatus {
    #[serde(rename = "EndedInStalemate")]
    EndedInStalemate,
    #[serde(rename = "EndedInWin")]
    EndedInWin,
    #[serde(rename = "InProgress")]
    InProgress,
    #[serde(rename = "NotStarted")]
    NotStarted,
}

impl ToString for PlayStatus {
    fn to_string(&self) -> String {
        match self {
            Self::EndedInStalemate => String::from("EndedInStalemate"),
            Self::EndedInWin => String::from("EndedInWin"),
            Self::InProgress => String::from("InProgress"),
            Self::NotStarted => String::from("NotStarted"),
        }
    }
}

impl Default for PlayStatus {
    fn default() -> PlayStatus {
        Self::EndedInStalemate
    }
}
