//
// AddPlayerParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models info needed to add a player to a game. */
public struct AddPlayerParams: Codable, JSONEncodable, Hashable {

    public var gameInvitationCode: String
    public var playerDisplayName: String

    public init(gameInvitationCode: String, playerDisplayName: String) {
        self.gameInvitationCode = gameInvitationCode
        self.playerDisplayName = playerDisplayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameInvitationCode = "game_invitation_code"
        case playerDisplayName = "player_display_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gameInvitationCode, forKey: .gameInvitationCode)
        try container.encode(playerDisplayName, forKey: .playerDisplayName)
    }
}

