//
// AutomaticPlayerSkillLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The skill level at which the Automatic Player is to play. */
public enum AutomaticPlayerSkillLevel: String, Codable, CaseIterable {
    case beginner = "Beginner"
    case intermediate = "Intermediate"
    case expert = "Expert"
    case master = "Master"
}
