//
// EndGamingSessionParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models info needed to end a Gaming Session. */
public struct EndGamingSessionParams: Codable, JSONEncodable, Hashable {

    public var playerId: String

    public init(playerId: String) {
        self.playerId = playerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case playerId = "player_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(playerId, forKey: .playerId)
    }
}

