//
// EndGameParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models info needed to end a Game */
public struct EndGameParams: Codable, JSONEncodable, Hashable {

    /** ID of one of the Players in the Gaming Session */
    public var playerId: String
    /** ID of the Gaming Session in which the Game is being played */
    public var sessionId: String

    public init(playerId: String, sessionId: String) {
        self.playerId = playerId
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case playerId = "player_id"
        case sessionId = "session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(playerId, forKey: .playerId)
        try container.encode(sessionId, forKey: .sessionId)
    }
}

