//
// EventTopicNames.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Names of the subscription topics used in the real-time messaging event plane. A full topic takes the form:  &#x60;[topic_prefix]/[event topic name]&#x60;  NOTE: The topic_prefix can be obtained from the event_plane_config field of the GameCreationResult model that is returned when creating a new game or when adding a new player to a Game. */
public enum EventTopicNames: String, Codable, CaseIterable {
    case gameEndedInStalemate = "GameEndedInStalemate"
    case gameEndedInWin = "GameEndedInWin"
    case playerAdded = "PlayerAdded"
    case turnTaken = "TurnTaken"
}
