//
// GameMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specifies the type of Game - single player or two players. */
public enum GameMode: String, Codable, CaseIterable {
    case singlePlayer = "SinglePlayer"
    case twoPlayers = "TwoPlayers"
}
