//
// GameCreationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models the results of a call to one of the Game creation endpoints */
public struct GameCreationResponse: Codable, JSONEncodable, Hashable {

    /** The initial Game state */
    public var gameInfo: GameInfoResponse
    /** The Player who initiated the Gaming Session */
    public var initiatingPlayer: PlayerInfo
    /** ID of the additional Player */
    public var otherPlayer: PlayerInfo?
    /** ID of the Gaming Session */
    public var sessionId: String

    public init(gameInfo: GameInfoResponse, initiatingPlayer: PlayerInfo, otherPlayer: PlayerInfo? = nil, sessionId: String) {
        self.gameInfo = gameInfo
        self.initiatingPlayer = initiatingPlayer
        self.otherPlayer = otherPlayer
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameInfo = "game_info"
        case initiatingPlayer = "initiating_player"
        case otherPlayer = "other_player"
        case sessionId = "session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gameInfo, forKey: .gameInfo)
        try container.encode(initiatingPlayer, forKey: .initiatingPlayer)
        try container.encodeIfPresent(otherPlayer, forKey: .otherPlayer)
        try container.encode(sessionId, forKey: .sessionId)
    }
}

