//
// GamePiece.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models a Game Piece with which the Tic-Tac-Toe game is played. */
public enum GamePiece: String, Codable, CaseIterable {
    case _none = "None"
    case x = "X"
    case o = "O"
}
