//
// GameTurnParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models info needed to perform a Game turn */
public struct GameTurnParams: Codable, JSONEncodable, Hashable {

    /** The location to which the Player's Game Piece is to be placed */
    public var destination: BoardPosition
    /** ID of the Player whose turn is being taken */
    public var playerId: String
    /** ID of the Gaming Session */
    public var sessionId: String

    public init(destination: BoardPosition, playerId: String, sessionId: String) {
        self.destination = destination
        self.playerId = playerId
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
        case playerId = "player_id"
        case sessionId = "session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(destination, forKey: .destination)
        try container.encode(playerId, forKey: .playerId)
        try container.encode(sessionId, forKey: .sessionId)
    }
}

