//
// GameInfoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models the current view of a Game */
public struct GameInfoResponse: Codable, JSONEncodable, Hashable {

    /** Player who has an open turn */
    public var currentPlayer: PlayerInfo?
    /** Unique ID of the Game instance */
    public var gameId: String
    /** The current state the Game */
    public var gameState: GameState
    /** List of Players */
    public var players: [PlayerInfo]

    public init(currentPlayer: PlayerInfo? = nil, gameId: String, gameState: GameState, players: [PlayerInfo]) {
        self.currentPlayer = currentPlayer
        self.gameId = gameId
        self.gameState = gameState
        self.players = players
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentPlayer = "current_player"
        case gameId = "game_id"
        case gameState = "game_state"
        case players
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currentPlayer, forKey: .currentPlayer)
        try container.encode(gameId, forKey: .gameId)
        try container.encode(gameState, forKey: .gameState)
        try container.encode(players, forKey: .players)
    }
}

