//
// GameState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * Defines Game State related structs and enums.  *  * © 2024 Rust Made Easy. All rights reserved.  * @author Joel@RustMadeEasy.com Models the state of a game at a particular move. */
public struct GameState: Codable, JSONEncodable, Hashable {

    public var gameBoard: [[GamePiece]]
    /** ID of the Player who made this Move. */
    public var idOfPlayerWhoMadeMove: String
    public var playStatus: PlayStatus
    public var winningLocations: [BoardPosition]?
    public var winningPlayerId: String?

    public init(gameBoard: [[GamePiece]], idOfPlayerWhoMadeMove: String, playStatus: PlayStatus, winningLocations: [BoardPosition]? = nil, winningPlayerId: String? = nil) {
        self.gameBoard = gameBoard
        self.idOfPlayerWhoMadeMove = idOfPlayerWhoMadeMove
        self.playStatus = playStatus
        self.winningLocations = winningLocations
        self.winningPlayerId = winningPlayerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameBoard = "game_board"
        case idOfPlayerWhoMadeMove = "id_of_player_who_made_move"
        case playStatus = "play_status"
        case winningLocations = "winning_locations"
        case winningPlayerId = "winning_player_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gameBoard, forKey: .gameBoard)
        try container.encode(idOfPlayerWhoMadeMove, forKey: .idOfPlayerWhoMadeMove)
        try container.encode(playStatus, forKey: .playStatus)
        try container.encodeIfPresent(winningLocations, forKey: .winningLocations)
        try container.encodeIfPresent(winningPlayerId, forKey: .winningPlayerId)
    }
}

