//
// GameCreationResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models the results of a call to the Create Game and Add Player endpoints. */
public struct GameCreationResult: Codable, JSONEncodable, Hashable {

    public var eventPlaneConfig: EventPlaneConfig
    public var gameInfo: GameInfo
    /** Code used to invite the second Player to the Game */
    public var gameInvitationCode: String

    public init(eventPlaneConfig: EventPlaneConfig, gameInfo: GameInfo, gameInvitationCode: String) {
        self.eventPlaneConfig = eventPlaneConfig
        self.gameInfo = gameInfo
        self.gameInvitationCode = gameInvitationCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventPlaneConfig = "event_plane_config"
        case gameInfo = "game_info"
        case gameInvitationCode = "game_invitation_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventPlaneConfig, forKey: .eventPlaneConfig)
        try container.encode(gameInfo, forKey: .gameInfo)
        try container.encode(gameInvitationCode, forKey: .gameInvitationCode)
    }
}

