//
// GameTurnInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models info needed to perform a Game turn. */
public struct GameTurnInfo: Codable, JSONEncodable, Hashable {

    public var destination: BoardPosition
    public var playerId: String

    public init(destination: BoardPosition, playerId: String) {
        self.destination = destination
        self.playerId = playerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
        case playerId = "player_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(destination, forKey: .destination)
        try container.encode(playerId, forKey: .playerId)
    }
}

