//
// GameState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models the state of a Game at a particular Move (turn). */
public struct GameState: Codable, JSONEncodable, Hashable {

    /** Specifies the layout of the Game Pieces for this particular Game State. */
    public var gameBoard: [[GamePiece]]
    /** ID of the Player who made the Move that brought about this Game State. */
    public var idOfPlayerWhoMadeMove: String
    /** The current status of the Game. */
    public var playStatus: PlayStatus

    public init(gameBoard: [[GamePiece]], idOfPlayerWhoMadeMove: String, playStatus: PlayStatus) {
        self.gameBoard = gameBoard
        self.idOfPlayerWhoMadeMove = idOfPlayerWhoMadeMove
        self.playStatus = playStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameBoard = "game_board"
        case idOfPlayerWhoMadeMove = "id_of_player_who_made_move"
        case playStatus = "play_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gameBoard, forKey: .gameBoard)
        try container.encode(idOfPlayerWhoMadeMove, forKey: .idOfPlayerWhoMadeMove)
        try container.encode(playStatus, forKey: .playStatus)
    }
}

