//
// NewGameParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models info needed to start a new Game. */
public struct NewGameParams: Codable, JSONEncodable, Hashable {

    public var playerOneDisplayName: String

    public init(playerOneDisplayName: String) {
        self.playerOneDisplayName = playerOneDisplayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case playerOneDisplayName = "player_one_display_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(playerOneDisplayName, forKey: .playerOneDisplayName)
    }
}

