//
// NewSinglePlayerGameParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models info needed to start a new Single-Player Game. */
public struct NewSinglePlayerGameParams: Codable, JSONEncodable, Hashable {

    public var computerSkillLevel: AutomaticPlayerSkillLevel

    public init(computerSkillLevel: AutomaticPlayerSkillLevel) {
        self.computerSkillLevel = computerSkillLevel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case computerSkillLevel = "computer_skill_level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(computerSkillLevel, forKey: .computerSkillLevel)
    }
}

