//
// PlayersReadinessResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models the results of a call to the Get Players&#39; Readiness end point */
public struct PlayersReadinessResponse: Codable, JSONEncodable, Hashable {

    /** Indicates whether the Game's Players are ready. */
    public var allPlayersAreReady: Bool

    public init(allPlayersAreReady: Bool) {
        self.allPlayersAreReady = allPlayersAreReady
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allPlayersAreReady = "all_players_are_ready"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allPlayersAreReady, forKey: .allPlayersAreReady)
    }
}

