//
// PlayStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Defines the valid Game play statuses */
public enum PlayStatus: String, Codable, CaseIterable {
    case endedInStalemate = "EndedInStalemate"
    case endedInWin = "EndedInWin"
    case inProgress = "InProgress"
    case notStarted = "NotStarted"
}
