//
// PlayerInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Models a Tic-Tac-Toe game Player. */
public struct PlayerInfo: Codable, JSONEncodable, Hashable {

    public var displayName: String
    public var gamePiece: GamePiece
    public var playerId: String

    public init(displayName: String, gamePiece: GamePiece, playerId: String) {
        self.displayName = displayName
        self.gamePiece = gamePiece
        self.playerId = playerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName = "display_name"
        case gamePiece = "game_piece"
        case playerId = "player_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(gamePiece, forKey: .gamePiece)
        try container.encode(playerId, forKey: .playerId)
    }
}

