[package]
name = "tic-tac-toe-service"
version = "0.2.0"
edition = "2021"

description = "Tic-Tac-Toe Game Service"
authors = ["Joel Davis <Joel@RustMadeEasy.com>"]
license = "GPL-3"

[dependencies]
actix-web = "4.5.1"
chrono = "0.4.37"
derive_more = "0.99.17"
env_logger = "0.11.2"
log = "0.4.21"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
utoipa = { version = "4.0.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }
uuid = { version = "1.7.0", features = ["v4"] }